# DOCKER_BUILDKIT=1 docker build --file Dockerfile.out --output out .
FROM node:12.19.1-slim as node-builder
ARG NPM_REGISTRY=https://registry.npm.taobao.org
ARG GOPROXY="https://mirrors.aliyun.com/goproxy/"
WORKDIR /vue-admin
COPY web/vue-admin .
RUN rm -rf vue.config.js &&\
    npm config set registry "$NPM_REGISTRY" && \
    npm install --unsafe-perm --registry=https://registry.npm.taobao.org --sass_binary_site=https://npm.taobao.org/mirrors/node-sass
RUN npm run build --scripts-prepend-node-path=auto

FROM centosgobuilder:1.16.4 AS go-builder
# install go
# yum install gcc git -y
WORKDIR /root/alertmanager_notifier
COPY . .
COPY --from=node-builder /vue-admin/dist web/dist
RUN /usr/local/go/bin/go env -w GOPROXY=https://goproxy.cn,direct
RUN CGO_ENABLED=1 GOOS=linux /usr/local/go/bin/go build -a -trimpath \
    -o bin/alertmanager_notifier \
    -ldflags "-X alertmanager_notifier/pkg/version.Version=`cat VERSION` -X alertmanager_notifier/pkg/version.Revision=`git rev-parse HEAD` -X alertmanager_notifier/pkg/version.Branch=`git rev-parse --abbrev-ref HEAD` -X alertmanager_notifier/pkg/version.BuildUser=`whoami` -X alertmanager_notifier/pkg/version.BuildDate=`date +%Y%m%d-%H:%M:%S`"  \
    cmd/alertmanager_notifier/main.go

FROM scratch AS export-stage
COPY --from=go-builder /root/alertmanager_notifier/bin/alertmanager_notifier ./bin/alertmanager_notifier-glibc217